version: '3.4'

services:
  ucabpagalotodoms:
    image: ${DOCKER_REGISTRY-}ucabpagalotodoms
    build:
      context: .
      dockerfile: UCABPagaloTodoMS/Dockerfile
    ports:
      - 5001:5001
      - 44339:44339
    depends_on:
        - postgres

  postgres:
    image: postgres
    environment:
      
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=pagalotodo
    ports:
    - 5432:5432
    volumes:
     - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 
